// Type Imports
import type { ChatData } from "@/features/chat/types";

// RetailOS internal staff/store messaging sample data.
// Reframed from the AdminCN chat demo: the conversation shape is unchanged
// (currentUser / contacts / conversations), only the people, roles, and message
// text are RetailOS-themed — store/warehouse/procurement/accounting staff across
// Georgetown, New Amsterdam, and Linden branches. No oRPC; sample-only.

const CURRENT_USER_ID = "user-me";

export const db: ChatData = {
  currentUser: {
    id: CURRENT_USER_ID,
    name: "Anita Persaud",
    avatar: "/images/avatars/avatar-1.webp",
    role: "Store Manager — Georgetown",
    status: "online",
    about:
      "Running the Georgetown flagship floor and coordinating end-of-day across registers.",
    email: "anita.persaud@retailos.gy",
    phone: "+592 600 1001",
    company: "RetailOS Guyana",
    country: "Guyana",
    website: "https://retailos.gy",
    timezone: "GYT (UTC-4)",
    location: "Georgetown, Guyana",
    availability: "Mon – Sat, 7 AM – 7 PM",
    tags: ["Store Manager", "Georgetown"],
    socialLinks: [{ platform: "website", url: "https://retailos.gy" }],
  },
  contacts: [
    {
      id: "contact-1",
      name: "Marcus Bourne",
      avatar: "/images/avatars/avatar-3.webp",
      role: "Head Cashier — Georgetown",
      status: "online",
      about: "Runs registers 1–4 and handles the morning float counts.",
      email: "marcus.bourne@retailos.gy",
      phone: "+592 600 1002",
      company: "RetailOS Guyana",
      country: "Guyana",
      timezone: "GYT (UTC-4)",
      location: "Georgetown, Guyana",
      availability: "Mon – Sat, 7 AM – 4 PM",
      tags: ["Cashier", "Georgetown"],
      socialLinks: [],
    },
    {
      id: "contact-2",
      name: "Ramesh Singh",
      avatar: "/images/avatars/avatar-5.webp",
      role: "Warehouse Lead — Georgetown",
      status: "busy",
      about: "Receiving, putaway, and replenishment for the main store.",
      email: "ramesh.singh@retailos.gy",
      phone: "+592 600 1003",
      company: "RetailOS Guyana",
      country: "Guyana",
      timezone: "GYT (UTC-4)",
      location: "Georgetown, Guyana",
      availability: "Mon – Sat, 6 AM – 3 PM",
      tags: ["Warehouse", "Georgetown"],
      socialLinks: [],
    },
    {
      id: "contact-3",
      name: "Devi Narine",
      avatar: "/images/avatars/avatar-7.webp",
      role: "Procurement Officer",
      status: "online",
      about: "Supplier orders, purchase approvals, and reorder planning.",
      email: "devi.narine@retailos.gy",
      phone: "+592 600 1004",
      company: "RetailOS Guyana",
      country: "Guyana",
      timezone: "GYT (UTC-4)",
      location: "Georgetown, Guyana",
      availability: "Mon – Fri, 8 AM – 5 PM",
      tags: ["Procurement"],
      socialLinks: [],
    },
    {
      id: "contact-4",
      name: "Joel Fraser",
      avatar: "/images/avatars/avatar-9.webp",
      role: "Accountant",
      status: "away",
      about: "AP/AR, drawer reconciliation, and monthly close.",
      email: "joel.fraser@retailos.gy",
      phone: "+592 600 1005",
      company: "RetailOS Guyana",
      country: "Guyana",
      timezone: "GYT (UTC-4)",
      location: "Georgetown, Guyana",
      availability: "Mon – Fri, 8 AM – 5 PM",
      tags: ["Accounting"],
      socialLinks: [],
    },
    {
      id: "contact-5",
      name: "Shanta Khan",
      avatar: "/images/avatars/avatar-2.webp",
      role: "Store Manager — New Amsterdam",
      status: "online",
      about: "Manages the New Amsterdam branch floor and transfers.",
      email: "shanta.khan@retailos.gy",
      phone: "+592 600 1006",
      company: "RetailOS Guyana",
      country: "Guyana",
      timezone: "GYT (UTC-4)",
      location: "New Amsterdam, Guyana",
      availability: "Mon – Sat, 7 AM – 7 PM",
      tags: ["Store Manager", "New Amsterdam"],
      socialLinks: [],
    },
    {
      id: "contact-6",
      name: "Trevor Adams",
      avatar: "/images/avatars/avatar-4.webp",
      role: "Bond Desk Officer",
      status: "busy",
      about: "Customs clearance, duty calc, and bonded-to-store releases.",
      email: "trevor.adams@retailos.gy",
      phone: "+592 600 1007",
      company: "RetailOS Guyana",
      country: "Guyana",
      timezone: "GYT (UTC-4)",
      location: "Georgetown, Guyana",
      availability: "Mon – Fri, 8 AM – 5 PM",
      tags: ["Bond Desk"],
      socialLinks: [],
    },
    {
      id: "contact-7",
      name: "Priya Mohan",
      avatar: "/images/avatars/avatar-6.webp",
      role: "Cashier — Linden",
      status: "offline",
      about: "Front register and customer pickups at the Linden branch.",
      email: "priya.mohan@retailos.gy",
      phone: "+592 600 1008",
      company: "RetailOS Guyana",
      country: "Guyana",
      timezone: "GYT (UTC-4)",
      location: "Linden, Guyana",
      availability: "Mon – Sat, 8 AM – 5 PM",
      tags: ["Cashier", "Linden"],
      socialLinks: [],
    },
    {
      id: "contact-8",
      name: "Errol Bacchus",
      avatar: "/images/avatars/avatar-8.webp",
      role: "Warehouse Lead — Linden",
      status: "away",
      about: "Receiving and stock counts for the Linden warehouse.",
      email: "errol.bacchus@retailos.gy",
      phone: "+592 600 1009",
      company: "RetailOS Guyana",
      country: "Guyana",
      timezone: "GYT (UTC-4)",
      location: "Linden, Guyana",
      availability: "Mon – Sat, 6 AM – 3 PM",
      tags: ["Warehouse", "Linden"],
      socialLinks: [],
    },
    {
      id: "contact-9",
      name: "Natasha Lall",
      avatar: "/images/avatars/avatar-10.webp",
      role: "Sales Representative",
      status: "online",
      about: "Wholesale accounts and commission-tracked floor sales.",
      email: "natasha.lall@retailos.gy",
      phone: "+592 600 1010",
      company: "RetailOS Guyana",
      country: "Guyana",
      timezone: "GYT (UTC-4)",
      location: "Georgetown, Guyana",
      availability: "Mon – Sat, 8 AM – 6 PM",
      tags: ["Sales"],
      socialLinks: [],
    },
    {
      id: "contact-10",
      name: "David Yhap",
      avatar: "/images/avatars/avatar-11.webp",
      role: "Regional Operations",
      status: "busy",
      about: "Oversees the Georgetown, New Amsterdam, and Linden branches.",
      email: "david.yhap@retailos.gy",
      phone: "+592 600 1011",
      company: "RetailOS Guyana",
      country: "Guyana",
      timezone: "GYT (UTC-4)",
      location: "Georgetown, Guyana",
      availability: "Mon – Fri, 8 AM – 6 PM",
      tags: ["Operations"],
      socialLinks: [],
    },
  ],
  conversations: [
    {
      id: "conv-1",
      type: "direct",
      contactId: "contact-1",
      isPinned: true,
      isMuted: false,
      isFavourite: true,
      unreadCount: 2,
      suggestions: [
        "On it now.",
        "Let me check the drawer report.",
        "Approved — go ahead.",
      ],
      autoReplies: [
        "Thanks, counting the float now.",
        "Register 2 is balanced again.",
        "I logged the over/short for you.",
        "Will close out at 7.",
        "Copy that.",
      ],
      messages: [
        {
          id: "msg-1-1",
          senderId: "contact-1",
          content:
            "Register 2 drawer is short GYD 1,500 at close. Want me to recount before the Z-report?",
          type: "text",
          timestamp: "2026-06-28T18:05:00.000Z",
          status: "read",
        },
        {
          id: "msg-1-2",
          senderId: CURRENT_USER_ID,
          content:
            "Yes, recount the GYD and USD trays separately and log the over/short.",
          type: "text",
          timestamp: "2026-06-28T18:09:00.000Z",
          status: "read",
        },
        {
          id: "msg-1-3",
          senderId: "contact-1",
          content:
            "Recounted — it was a USD note in the wrong tray. Drawer balances now.",
          type: "text",
          timestamp: "2026-06-28T18:22:00.000Z",
          status: "read",
        },
        {
          id: "msg-1-4",
          senderId: "contact-1",
          content: "Sending the blind-close sheet for your sign-off.",
          type: "file",
          timestamp: "2026-06-28T18:24:00.000Z",
          status: "delivered",
          attachments: [
            {
              id: "att-1-1",
              name: "register-2-blind-close.pdf",
              size: "184 KB",
              type: "file",
              url: "/files/register-2-blind-close.pdf",
            },
          ],
        },
        {
          id: "msg-1-5",
          senderId: "contact-1",
          content:
            "Also, can you approve a price override for the damaged cooler box?",
          type: "text",
          timestamp: "2026-06-29T08:02:00.000Z",
          status: "delivered",
        },
      ],
    },
    {
      id: "conv-2",
      type: "direct",
      contactId: "contact-3",
      isPinned: true,
      isMuted: false,
      isFavourite: false,
      unreadCount: 1,
      suggestions: [
        "Approved.",
        "Hold that PO for now.",
        "Check the supplier terms first.",
      ],
      autoReplies: [
        "PO sent to the supplier.",
        "Reorder list updated.",
        "Waiting on the vendor quote.",
        "Will confirm by noon.",
      ],
      messages: [
        {
          id: "msg-2-1",
          senderId: "contact-3",
          content:
            "PO-0241 for Ramnarine Hardware needs your approval — GYD 1.2M, 30-day terms.",
          type: "text",
          timestamp: "2026-06-29T07:40:00.000Z",
          status: "read",
        },
        {
          id: "msg-2-2",
          senderId: CURRENT_USER_ID,
          content: "Does it include the rebar reorder Ramesh flagged?",
          type: "text",
          timestamp: "2026-06-29T07:44:00.000Z",
          status: "read",
        },
        {
          id: "msg-2-3",
          senderId: "contact-3",
          content: "Yes — 200 lengths of 12mm rebar plus the cement reorder.",
          type: "text",
          timestamp: "2026-06-29T07:46:00.000Z",
          status: "delivered",
        },
      ],
    },
    {
      id: "conv-3",
      type: "direct",
      contactId: "contact-2",
      isPinned: false,
      isMuted: false,
      isFavourite: true,
      unreadCount: 0,
      suggestions: [
        "Receive it into bonded.",
        "Count it first.",
        "Move it to the floor.",
      ],
      autoReplies: [
        "Putaway done.",
        "Counted and posted.",
        "Stock ledger updated.",
      ],
      messages: [
        {
          id: "msg-3-1",
          senderId: "contact-2",
          content: "Low stock on rebar 12mm — down to 18 lengths. Reorder?",
          type: "text",
          timestamp: "2026-06-28T09:10:00.000Z",
          status: "read",
        },
        {
          id: "msg-3-2",
          senderId: CURRENT_USER_ID,
          content:
            "Devi is raising PO-0241 now. Pull a cycle count so the numbers match before receiving.",
          type: "text",
          timestamp: "2026-06-28T09:15:00.000Z",
          status: "read",
        },
        {
          id: "msg-3-3",
          senderId: "contact-2",
          content: "Cycle count done. Photo of the rack for the record.",
          type: "image",
          timestamp: "2026-06-28T09:42:00.000Z",
          status: "read",
          attachments: [
            {
              id: "att-3-1",
              name: "rebar-rack-a3.jpg",
              size: "1.1 MB",
              type: "image",
              url: "/images/chat/rebar-rack.jpg",
            },
          ],
        },
      ],
    },
    {
      id: "conv-4",
      type: "direct",
      contactId: "contact-6",
      isPinned: false,
      isMuted: false,
      isFavourite: false,
      unreadCount: 3,
      suggestions: [
        "Release to Georgetown.",
        "Hold for duty.",
        "Send the customs docs.",
      ],
      autoReplies: [
        "Duty calculated.",
        "Release posted to the store.",
        "Customs reference attached.",
        "Bonded balance updated.",
      ],
      messages: [
        {
          id: "msg-4-1",
          senderId: "contact-6",
          content:
            "Bonded container GU-77421 cleared customs. Releasing to Georgetown store?",
          type: "text",
          timestamp: "2026-06-29T06:30:00.000Z",
          status: "read",
        },
        {
          id: "msg-4-2",
          senderId: CURRENT_USER_ID,
          content:
            "Yes — release the full pallet of power tools. What is the duty + VAT total?",
          type: "text",
          timestamp: "2026-06-29T06:35:00.000Z",
          status: "read",
        },
        {
          id: "msg-4-3",
          senderId: "contact-6",
          content:
            "Duty GYD 84,000 and VAT GYD 96,000. I will add it as landed cost on release.",
          type: "text",
          timestamp: "2026-06-29T06:38:00.000Z",
          status: "delivered",
        },
        {
          id: "msg-4-4",
          senderId: "contact-6",
          content: "Customs clearance certificate for the file.",
          type: "file",
          timestamp: "2026-06-29T06:40:00.000Z",
          status: "delivered",
          attachments: [
            {
              id: "att-4-1",
              name: "customs-clearance-GU-77421.pdf",
              size: "312 KB",
              type: "file",
              url: "/files/customs-clearance.pdf",
            },
          ],
        },
      ],
    },
    {
      id: "conv-5",
      type: "direct",
      contactId: "contact-4",
      isPinned: false,
      isMuted: true,
      isFavourite: false,
      unreadCount: 0,
      suggestions: [
        "Sending it now.",
        "Already reconciled.",
        "Check the cash-clearing account.",
      ],
      autoReplies: [
        "Posted to the GL.",
        "Reconciled — thanks.",
        "Variance noted.",
      ],
      messages: [
        {
          id: "msg-5-1",
          senderId: "contact-4",
          content:
            "Yesterday's POS settlement does not match the bank deposit by GYD 2,300. Can you confirm the drawer counts?",
          type: "text",
          timestamp: "2026-06-28T16:20:00.000Z",
          status: "read",
        },
        {
          id: "msg-5-2",
          senderId: CURRENT_USER_ID,
          content:
            "That is the register-2 over/short Marcus already logged. Tie it to the cash-clearing account.",
          type: "text",
          timestamp: "2026-06-28T16:28:00.000Z",
          status: "read",
        },
        {
          id: "msg-5-3",
          senderId: "contact-4",
          content: "Found it — reconciled. Closing the day.",
          type: "text",
          timestamp: "2026-06-28T16:33:00.000Z",
          status: "read",
        },
      ],
    },
    {
      id: "conv-6",
      type: "direct",
      contactId: "contact-5",
      isPinned: false,
      isMuted: false,
      isFavourite: false,
      unreadCount: 1,
      suggestions: [
        "Approve the transfer.",
        "Ship today.",
        "Check stock first.",
      ],
      autoReplies: [
        "Transfer received.",
        "Shipped — tracking attached.",
        "Stock confirmed.",
      ],
      messages: [
        {
          id: "msg-6-1",
          senderId: "contact-5",
          content:
            "New Amsterdam is out of the 5L paint. Can Georgetown transfer 40 units?",
          type: "text",
          timestamp: "2026-06-29T08:50:00.000Z",
          status: "read",
        },
        {
          id: "msg-6-2",
          senderId: CURRENT_USER_ID,
          content:
            "We can spare 40. I will raise the intra-company transfer and ship this afternoon.",
          type: "text",
          timestamp: "2026-06-29T08:55:00.000Z",
          status: "delivered",
        },
      ],
    },
    {
      id: "conv-7",
      type: "direct",
      contactId: "contact-9",
      isPinned: false,
      isMuted: false,
      isFavourite: false,
      unreadCount: 0,
      suggestions: [
        "Apply the wholesale price.",
        "Check the credit limit.",
        "Confirm the order.",
      ],
      autoReplies: [
        "Order placed.",
        "Commission logged.",
        "Customer confirmed.",
      ],
      messages: [
        {
          id: "msg-7-1",
          senderId: "contact-9",
          content:
            "Wholesale customer Demerara Builders wants 300 bags of cement. They are near their credit limit though.",
          type: "text",
          timestamp: "2026-06-27T11:05:00.000Z",
          status: "read",
        },
        {
          id: "msg-7-2",
          senderId: CURRENT_USER_ID,
          content:
            "Hold the order until Joel confirms their balance. Apply tier-2 wholesale pricing if it clears.",
          type: "text",
          timestamp: "2026-06-27T11:12:00.000Z",
          status: "read",
        },
      ],
    },
    {
      id: "conv-8",
      type: "group",
      groupName: "Georgetown Store Floor",
      groupAvatar: "/images/avatars/avatar-3.webp",
      memberIds: [CURRENT_USER_ID, "contact-1", "contact-2", "contact-9"],
      isPinned: true,
      isMuted: false,
      isFavourite: true,
      unreadCount: 4,
      suggestions: ["Opening in 10.", "Floats are ready.", "Doors open."],
      autoReplies: ["Registers up.", "Floor stocked.", "All set."],
      messages: [
        {
          id: "msg-8-1",
          senderId: CURRENT_USER_ID,
          content:
            "Morning team — promo on the cooler boxes starts today, 15% off. Update the shelf tags.",
          type: "text",
          timestamp: "2026-06-29T06:55:00.000Z",
          status: "read",
        },
        {
          id: "msg-8-2",
          senderId: "contact-2",
          content: "Tags printed and on the shelves.",
          type: "text",
          timestamp: "2026-06-29T07:05:00.000Z",
          status: "read",
        },
        {
          id: "msg-8-3",
          senderId: "contact-1",
          content: "Floats counted, registers 1–4 open.",
          type: "text",
          timestamp: "2026-06-29T07:08:00.000Z",
          status: "read",
        },
        {
          id: "msg-8-4",
          senderId: "contact-9",
          content:
            "Two wholesale pickups scheduled before noon — I will handle them at the desk.",
          type: "text",
          timestamp: "2026-06-29T07:11:00.000Z",
          status: "delivered",
        },
      ],
    },
    {
      id: "conv-9",
      type: "group",
      groupName: "Procurement & Bond",
      groupAvatar: "/images/avatars/avatar-7.webp",
      memberIds: [CURRENT_USER_ID, "contact-3", "contact-6", "contact-4"],
      isPinned: false,
      isMuted: false,
      isFavourite: false,
      unreadCount: 0,
      suggestions: ["Approve.", "Hold for clearance.", "Add to landed cost."],
      autoReplies: ["PO approved.", "Cleared customs.", "Cost allocated."],
      messages: [
        {
          id: "msg-9-1",
          senderId: "contact-3",
          content:
            "Container of power tools lands Thursday. Bond, can you pre-stage the customs paperwork?",
          type: "text",
          timestamp: "2026-06-28T13:20:00.000Z",
          status: "read",
        },
        {
          id: "msg-9-2",
          senderId: "contact-6",
          content:
            "Already drafted. I will need the supplier invoice to finalize the duty estimate.",
          type: "text",
          timestamp: "2026-06-28T13:26:00.000Z",
          status: "read",
        },
        {
          id: "msg-9-3",
          senderId: "contact-4",
          content:
            "Make sure freight and insurance are split into the landed cost so COGS stays accurate.",
          type: "text",
          timestamp: "2026-06-28T13:31:00.000Z",
          status: "read",
        },
      ],
    },
    {
      id: "conv-10",
      type: "group",
      groupName: "Branch Managers",
      groupAvatar: "/images/avatars/avatar-2.webp",
      memberIds: [CURRENT_USER_ID, "contact-5", "contact-10"],
      isPinned: false,
      isMuted: false,
      isFavourite: false,
      unreadCount: 1,
      suggestions: [
        "Numbers look good.",
        "Let us sync Friday.",
        "I will send the report.",
      ],
      autoReplies: [
        "Report shared.",
        "On track for target.",
        "Will review tonight.",
      ],
      messages: [
        {
          id: "msg-10-1",
          senderId: "contact-10",
          content:
            "Weekly sales across all three branches are up 8%. Georgetown leads, Linden is lagging on footfall.",
          type: "text",
          timestamp: "2026-06-28T17:00:00.000Z",
          status: "read",
        },
        {
          id: "msg-10-2",
          senderId: "contact-5",
          content:
            "New Amsterdam hit target after the paint transfer. Thanks Anita.",
          type: "text",
          timestamp: "2026-06-28T17:06:00.000Z",
          status: "read",
        },
        {
          id: "msg-10-3",
          senderId: "contact-10",
          content:
            "Let us run a weekend promo at Linden to lift footfall. Sales-by-store report attached.",
          type: "file",
          timestamp: "2026-06-28T17:12:00.000Z",
          status: "delivered",
          attachments: [
            {
              id: "att-10-1",
              name: "weekly-sales-by-store.pdf",
              size: "256 KB",
              type: "file",
              url: "/files/weekly-sales-by-store.pdf",
            },
          ],
        },
      ],
    },
  ],
};
