/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVariantsRouteImport } from './routes/_app/variants'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppUomConversionsRouteImport } from './routes/_app/uom-conversions'
import { Route as AppUnitsRouteImport } from './routes/_app/units'
import { Route as AppTransfersRouteImport } from './routes/_app/transfers'
import { Route as AppStockLedgerRouteImport } from './routes/_app/stock-ledger'
import { Route as AppSkusRouteImport } from './routes/_app/skus'
import { Route as AppShiftsRouteImport } from './routes/_app/shifts'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSalesRouteImport } from './routes/_app/sales'
import { Route as AppRolesRouteImport } from './routes/_app/roles'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppPricingRouteImport } from './routes/_app/pricing'
import { Route as AppPosRouteImport } from './routes/_app/pos'
import { Route as AppPermissionsRouteImport } from './routes/_app/permissions'
import { Route as AppOrdersRouteImport } from './routes/_app/orders'
import { Route as AppOnboardingRouteImport } from './routes/_app/onboarding'
import { Route as AppLotsRouteImport } from './routes/_app/lots'
import { Route as AppLogisticsRouteImport } from './routes/_app/logistics'
import { Route as AppLocationsRouteImport } from './routes/_app/locations'
import { Route as AppInventoryRouteImport } from './routes/_app/inventory'
import { Route as AppFinanceRouteImport } from './routes/_app/finance'
import { Route as AppFaqRouteImport } from './routes/_app/faq'
import { Route as AppEmptyStatesRouteImport } from './routes/_app/empty-states'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCommerceDashboardRouteImport } from './routes/_app/commerce-dashboard'
import { Route as AppCategoriesRouteImport } from './routes/_app/categories'
import { Route as AppBrandsRouteImport } from './routes/_app/brands'
import { Route as AppBondsRouteImport } from './routes/_app/bonds'
import { Route as AppBarcodesRouteImport } from './routes/_app/barcodes'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppProductsIndexRouteImport } from './routes/_app/products.index'
import { Route as AppReportsNumberLeasesRouteImport } from './routes/_app/reports.number-leases'
import { Route as AppReportsFinancialRouteImport } from './routes/_app/reports.financial'
import { Route as AppProductsProductIdRouteImport } from './routes/_app/products.$productId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVariantsRoute = AppVariantsRouteImport.update({
  id: '/variants',
  path: '/variants',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUomConversionsRoute = AppUomConversionsRouteImport.update({
  id: '/uom-conversions',
  path: '/uom-conversions',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUnitsRoute = AppUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTransfersRoute = AppTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppStockLedgerRoute = AppStockLedgerRouteImport.update({
  id: '/stock-ledger',
  path: '/stock-ledger',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSkusRoute = AppSkusRouteImport.update({
  id: '/skus',
  path: '/skus',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppShiftsRoute = AppShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRolesRoute = AppRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPricingRoute = AppPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPosRoute = AppPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPermissionsRoute = AppPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLotsRoute = AppLotsRouteImport.update({
  id: '/lots',
  path: '/lots',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLogisticsRoute = AppLogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLocationsRoute = AppLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFaqRoute = AppFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEmptyStatesRoute = AppEmptyStatesRouteImport.update({
  id: '/empty-states',
  path: '/empty-states',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCommerceDashboardRoute = AppCommerceDashboardRouteImport.update({
  id: '/commerce-dashboard',
  path: '/commerce-dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCategoriesRoute = AppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBrandsRoute = AppBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBondsRoute = AppBondsRouteImport.update({
  id: '/bonds',
  path: '/bonds',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBarcodesRoute = AppBarcodesRouteImport.update({
  id: '/barcodes',
  path: '/barcodes',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReportsNumberLeasesRoute = AppReportsNumberLeasesRouteImport.update({
  id: '/reports/number-leases',
  path: '/reports/number-leases',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReportsFinancialRoute = AppReportsFinancialRouteImport.update({
  id: '/reports/financial',
  path: '/reports/financial',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProductsProductIdRoute = AppProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AppAnalyticsRoute
  '/barcodes': typeof AppBarcodesRoute
  '/bonds': typeof AppBondsRoute
  '/brands': typeof AppBrandsRoute
  '/categories': typeof AppCategoriesRoute
  '/commerce-dashboard': typeof AppCommerceDashboardRoute
  '/dashboard': typeof AppDashboardRoute
  '/empty-states': typeof AppEmptyStatesRoute
  '/faq': typeof AppFaqRoute
  '/finance': typeof AppFinanceRoute
  '/inventory': typeof AppInventoryRoute
  '/locations': typeof AppLocationsRoute
  '/logistics': typeof AppLogisticsRoute
  '/lots': typeof AppLotsRoute
  '/onboarding': typeof AppOnboardingRoute
  '/orders': typeof AppOrdersRoute
  '/permissions': typeof AppPermissionsRoute
  '/pos': typeof AppPosRoute
  '/pricing': typeof AppPricingRoute
  '/profile': typeof AppProfileRoute
  '/roles': typeof AppRolesRoute
  '/sales': typeof AppSalesRoute
  '/settings': typeof AppSettingsRoute
  '/shifts': typeof AppShiftsRoute
  '/skus': typeof AppSkusRoute
  '/stock-ledger': typeof AppStockLedgerRoute
  '/transfers': typeof AppTransfersRoute
  '/units': typeof AppUnitsRoute
  '/uom-conversions': typeof AppUomConversionsRoute
  '/users': typeof AppUsersRoute
  '/variants': typeof AppVariantsRoute
  '/products/$productId': typeof AppProductsProductIdRoute
  '/reports/financial': typeof AppReportsFinancialRoute
  '/reports/number-leases': typeof AppReportsNumberLeasesRoute
  '/products/': typeof AppProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AppAnalyticsRoute
  '/barcodes': typeof AppBarcodesRoute
  '/bonds': typeof AppBondsRoute
  '/brands': typeof AppBrandsRoute
  '/categories': typeof AppCategoriesRoute
  '/commerce-dashboard': typeof AppCommerceDashboardRoute
  '/dashboard': typeof AppDashboardRoute
  '/empty-states': typeof AppEmptyStatesRoute
  '/faq': typeof AppFaqRoute
  '/finance': typeof AppFinanceRoute
  '/inventory': typeof AppInventoryRoute
  '/locations': typeof AppLocationsRoute
  '/logistics': typeof AppLogisticsRoute
  '/lots': typeof AppLotsRoute
  '/onboarding': typeof AppOnboardingRoute
  '/orders': typeof AppOrdersRoute
  '/permissions': typeof AppPermissionsRoute
  '/pos': typeof AppPosRoute
  '/pricing': typeof AppPricingRoute
  '/profile': typeof AppProfileRoute
  '/roles': typeof AppRolesRoute
  '/sales': typeof AppSalesRoute
  '/settings': typeof AppSettingsRoute
  '/shifts': typeof AppShiftsRoute
  '/skus': typeof AppSkusRoute
  '/stock-ledger': typeof AppStockLedgerRoute
  '/transfers': typeof AppTransfersRoute
  '/units': typeof AppUnitsRoute
  '/uom-conversions': typeof AppUomConversionsRoute
  '/users': typeof AppUsersRoute
  '/variants': typeof AppVariantsRoute
  '/products/$productId': typeof AppProductsProductIdRoute
  '/reports/financial': typeof AppReportsFinancialRoute
  '/reports/number-leases': typeof AppReportsNumberLeasesRoute
  '/products': typeof AppProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/barcodes': typeof AppBarcodesRoute
  '/_app/bonds': typeof AppBondsRoute
  '/_app/brands': typeof AppBrandsRoute
  '/_app/categories': typeof AppCategoriesRoute
  '/_app/commerce-dashboard': typeof AppCommerceDashboardRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/empty-states': typeof AppEmptyStatesRoute
  '/_app/faq': typeof AppFaqRoute
  '/_app/finance': typeof AppFinanceRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/locations': typeof AppLocationsRoute
  '/_app/logistics': typeof AppLogisticsRoute
  '/_app/lots': typeof AppLotsRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/orders': typeof AppOrdersRoute
  '/_app/permissions': typeof AppPermissionsRoute
  '/_app/pos': typeof AppPosRoute
  '/_app/pricing': typeof AppPricingRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/roles': typeof AppRolesRoute
  '/_app/sales': typeof AppSalesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/shifts': typeof AppShiftsRoute
  '/_app/skus': typeof AppSkusRoute
  '/_app/stock-ledger': typeof AppStockLedgerRoute
  '/_app/transfers': typeof AppTransfersRoute
  '/_app/units': typeof AppUnitsRoute
  '/_app/uom-conversions': typeof AppUomConversionsRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/variants': typeof AppVariantsRoute
  '/_app/products/$productId': typeof AppProductsProductIdRoute
  '/_app/reports/financial': typeof AppReportsFinancialRoute
  '/_app/reports/number-leases': typeof AppReportsNumberLeasesRoute
  '/_app/products/': typeof AppProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/analytics'
    | '/barcodes'
    | '/bonds'
    | '/brands'
    | '/categories'
    | '/commerce-dashboard'
    | '/dashboard'
    | '/empty-states'
    | '/faq'
    | '/finance'
    | '/inventory'
    | '/locations'
    | '/logistics'
    | '/lots'
    | '/onboarding'
    | '/orders'
    | '/permissions'
    | '/pos'
    | '/pricing'
    | '/profile'
    | '/roles'
    | '/sales'
    | '/settings'
    | '/shifts'
    | '/skus'
    | '/stock-ledger'
    | '/transfers'
    | '/units'
    | '/uom-conversions'
    | '/users'
    | '/variants'
    | '/products/$productId'
    | '/reports/financial'
    | '/reports/number-leases'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/analytics'
    | '/barcodes'
    | '/bonds'
    | '/brands'
    | '/categories'
    | '/commerce-dashboard'
    | '/dashboard'
    | '/empty-states'
    | '/faq'
    | '/finance'
    | '/inventory'
    | '/locations'
    | '/logistics'
    | '/lots'
    | '/onboarding'
    | '/orders'
    | '/permissions'
    | '/pos'
    | '/pricing'
    | '/profile'
    | '/roles'
    | '/sales'
    | '/settings'
    | '/shifts'
    | '/skus'
    | '/stock-ledger'
    | '/transfers'
    | '/units'
    | '/uom-conversions'
    | '/users'
    | '/variants'
    | '/products/$productId'
    | '/reports/financial'
    | '/reports/number-leases'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/analytics'
    | '/_app/barcodes'
    | '/_app/bonds'
    | '/_app/brands'
    | '/_app/categories'
    | '/_app/commerce-dashboard'
    | '/_app/dashboard'
    | '/_app/empty-states'
    | '/_app/faq'
    | '/_app/finance'
    | '/_app/inventory'
    | '/_app/locations'
    | '/_app/logistics'
    | '/_app/lots'
    | '/_app/onboarding'
    | '/_app/orders'
    | '/_app/permissions'
    | '/_app/pos'
    | '/_app/pricing'
    | '/_app/profile'
    | '/_app/roles'
    | '/_app/sales'
    | '/_app/settings'
    | '/_app/shifts'
    | '/_app/skus'
    | '/_app/stock-ledger'
    | '/_app/transfers'
    | '/_app/units'
    | '/_app/uom-conversions'
    | '/_app/users'
    | '/_app/variants'
    | '/_app/products/$productId'
    | '/_app/reports/financial'
    | '/_app/reports/number-leases'
    | '/_app/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/variants': {
      id: '/_app/variants'
      path: '/variants'
      fullPath: '/variants'
      preLoaderRoute: typeof AppVariantsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/uom-conversions': {
      id: '/_app/uom-conversions'
      path: '/uom-conversions'
      fullPath: '/uom-conversions'
      preLoaderRoute: typeof AppUomConversionsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/units': {
      id: '/_app/units'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof AppUnitsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/transfers': {
      id: '/_app/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof AppTransfersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/stock-ledger': {
      id: '/_app/stock-ledger'
      path: '/stock-ledger'
      fullPath: '/stock-ledger'
      preLoaderRoute: typeof AppStockLedgerRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/skus': {
      id: '/_app/skus'
      path: '/skus'
      fullPath: '/skus'
      preLoaderRoute: typeof AppSkusRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/shifts': {
      id: '/_app/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof AppShiftsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/sales': {
      id: '/_app/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/roles': {
      id: '/_app/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AppRolesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/pricing': {
      id: '/_app/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof AppPricingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/pos': {
      id: '/_app/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AppPosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/permissions': {
      id: '/_app/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof AppPermissionsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/orders': {
      id: '/_app/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/lots': {
      id: '/_app/lots'
      path: '/lots'
      fullPath: '/lots'
      preLoaderRoute: typeof AppLotsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/logistics': {
      id: '/_app/logistics'
      path: '/logistics'
      fullPath: '/logistics'
      preLoaderRoute: typeof AppLogisticsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/locations': {
      id: '/_app/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof AppLocationsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/finance': {
      id: '/_app/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/faq': {
      id: '/_app/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof AppFaqRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/empty-states': {
      id: '/_app/empty-states'
      path: '/empty-states'
      fullPath: '/empty-states'
      preLoaderRoute: typeof AppEmptyStatesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/commerce-dashboard': {
      id: '/_app/commerce-dashboard'
      path: '/commerce-dashboard'
      fullPath: '/commerce-dashboard'
      preLoaderRoute: typeof AppCommerceDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/categories': {
      id: '/_app/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AppCategoriesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/brands': {
      id: '/_app/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof AppBrandsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/bonds': {
      id: '/_app/bonds'
      path: '/bonds'
      fullPath: '/bonds'
      preLoaderRoute: typeof AppBondsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/barcodes': {
      id: '/_app/barcodes'
      path: '/barcodes'
      fullPath: '/barcodes'
      preLoaderRoute: typeof AppBarcodesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/products/': {
      id: '/_app/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/reports/number-leases': {
      id: '/_app/reports/number-leases'
      path: '/reports/number-leases'
      fullPath: '/reports/number-leases'
      preLoaderRoute: typeof AppReportsNumberLeasesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/reports/financial': {
      id: '/_app/reports/financial'
      path: '/reports/financial'
      fullPath: '/reports/financial'
      preLoaderRoute: typeof AppReportsFinancialRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/products/$productId': {
      id: '/_app/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof AppProductsProductIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppBarcodesRoute: typeof AppBarcodesRoute
  AppBondsRoute: typeof AppBondsRoute
  AppBrandsRoute: typeof AppBrandsRoute
  AppCategoriesRoute: typeof AppCategoriesRoute
  AppCommerceDashboardRoute: typeof AppCommerceDashboardRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEmptyStatesRoute: typeof AppEmptyStatesRoute
  AppFaqRoute: typeof AppFaqRoute
  AppFinanceRoute: typeof AppFinanceRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppLocationsRoute: typeof AppLocationsRoute
  AppLogisticsRoute: typeof AppLogisticsRoute
  AppLotsRoute: typeof AppLotsRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppPermissionsRoute: typeof AppPermissionsRoute
  AppPosRoute: typeof AppPosRoute
  AppPricingRoute: typeof AppPricingRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRolesRoute: typeof AppRolesRoute
  AppSalesRoute: typeof AppSalesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppShiftsRoute: typeof AppShiftsRoute
  AppSkusRoute: typeof AppSkusRoute
  AppStockLedgerRoute: typeof AppStockLedgerRoute
  AppTransfersRoute: typeof AppTransfersRoute
  AppUnitsRoute: typeof AppUnitsRoute
  AppUomConversionsRoute: typeof AppUomConversionsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppVariantsRoute: typeof AppVariantsRoute
  AppProductsProductIdRoute: typeof AppProductsProductIdRoute
  AppReportsFinancialRoute: typeof AppReportsFinancialRoute
  AppReportsNumberLeasesRoute: typeof AppReportsNumberLeasesRoute
  AppProductsIndexRoute: typeof AppProductsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppBarcodesRoute: AppBarcodesRoute,
  AppBondsRoute: AppBondsRoute,
  AppBrandsRoute: AppBrandsRoute,
  AppCategoriesRoute: AppCategoriesRoute,
  AppCommerceDashboardRoute: AppCommerceDashboardRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEmptyStatesRoute: AppEmptyStatesRoute,
  AppFaqRoute: AppFaqRoute,
  AppFinanceRoute: AppFinanceRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppLocationsRoute: AppLocationsRoute,
  AppLogisticsRoute: AppLogisticsRoute,
  AppLotsRoute: AppLotsRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppPermissionsRoute: AppPermissionsRoute,
  AppPosRoute: AppPosRoute,
  AppPricingRoute: AppPricingRoute,
  AppProfileRoute: AppProfileRoute,
  AppRolesRoute: AppRolesRoute,
  AppSalesRoute: AppSalesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppShiftsRoute: AppShiftsRoute,
  AppSkusRoute: AppSkusRoute,
  AppStockLedgerRoute: AppStockLedgerRoute,
  AppTransfersRoute: AppTransfersRoute,
  AppUnitsRoute: AppUnitsRoute,
  AppUomConversionsRoute: AppUomConversionsRoute,
  AppUsersRoute: AppUsersRoute,
  AppVariantsRoute: AppVariantsRoute,
  AppProductsProductIdRoute: AppProductsProductIdRoute,
  AppReportsFinancialRoute: AppReportsFinancialRoute,
  AppReportsNumberLeasesRoute: AppReportsNumberLeasesRoute,
  AppProductsIndexRoute: AppProductsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
