/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUnitsRouteImport } from './routes/_app/units'
import { Route as AppTransfersRouteImport } from './routes/_app/transfers'
import { Route as AppStockLedgerRouteImport } from './routes/_app/stock-ledger'
import { Route as AppSkusRouteImport } from './routes/_app/skus'
import { Route as AppShiftsRouteImport } from './routes/_app/shifts'
import { Route as AppSalesRouteImport } from './routes/_app/sales'
import { Route as AppPosRouteImport } from './routes/_app/pos'
import { Route as AppLocationsRouteImport } from './routes/_app/locations'
import { Route as AppInventoryRouteImport } from './routes/_app/inventory'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCategoriesRouteImport } from './routes/_app/categories'
import { Route as AppBrandsRouteImport } from './routes/_app/brands'
import { Route as AppBondsRouteImport } from './routes/_app/bonds'
import { Route as AppBarcodesRouteImport } from './routes/_app/barcodes'
import { Route as AppProductsIndexRouteImport } from './routes/_app/products.index'
import { Route as AppReportsNumberLeasesRouteImport } from './routes/_app/reports.number-leases'
import { Route as AppReportsFinancialRouteImport } from './routes/_app/reports.financial'
import { Route as AppProductsProductIdRouteImport } from './routes/_app/products.$productId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUnitsRoute = AppUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTransfersRoute = AppTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppStockLedgerRoute = AppStockLedgerRouteImport.update({
  id: '/stock-ledger',
  path: '/stock-ledger',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSkusRoute = AppSkusRouteImport.update({
  id: '/skus',
  path: '/skus',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppShiftsRoute = AppShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPosRoute = AppPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLocationsRoute = AppLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCategoriesRoute = AppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBrandsRoute = AppBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBondsRoute = AppBondsRouteImport.update({
  id: '/bonds',
  path: '/bonds',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBarcodesRoute = AppBarcodesRouteImport.update({
  id: '/barcodes',
  path: '/barcodes',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReportsNumberLeasesRoute = AppReportsNumberLeasesRouteImport.update({
  id: '/reports/number-leases',
  path: '/reports/number-leases',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReportsFinancialRoute = AppReportsFinancialRouteImport.update({
  id: '/reports/financial',
  path: '/reports/financial',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProductsProductIdRoute = AppProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/barcodes': typeof AppBarcodesRoute
  '/bonds': typeof AppBondsRoute
  '/brands': typeof AppBrandsRoute
  '/categories': typeof AppCategoriesRoute
  '/dashboard': typeof AppDashboardRoute
  '/inventory': typeof AppInventoryRoute
  '/locations': typeof AppLocationsRoute
  '/pos': typeof AppPosRoute
  '/sales': typeof AppSalesRoute
  '/shifts': typeof AppShiftsRoute
  '/skus': typeof AppSkusRoute
  '/stock-ledger': typeof AppStockLedgerRoute
  '/transfers': typeof AppTransfersRoute
  '/units': typeof AppUnitsRoute
  '/products/$productId': typeof AppProductsProductIdRoute
  '/reports/financial': typeof AppReportsFinancialRoute
  '/reports/number-leases': typeof AppReportsNumberLeasesRoute
  '/products/': typeof AppProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/barcodes': typeof AppBarcodesRoute
  '/bonds': typeof AppBondsRoute
  '/brands': typeof AppBrandsRoute
  '/categories': typeof AppCategoriesRoute
  '/dashboard': typeof AppDashboardRoute
  '/inventory': typeof AppInventoryRoute
  '/locations': typeof AppLocationsRoute
  '/pos': typeof AppPosRoute
  '/sales': typeof AppSalesRoute
  '/shifts': typeof AppShiftsRoute
  '/skus': typeof AppSkusRoute
  '/stock-ledger': typeof AppStockLedgerRoute
  '/transfers': typeof AppTransfersRoute
  '/units': typeof AppUnitsRoute
  '/products/$productId': typeof AppProductsProductIdRoute
  '/reports/financial': typeof AppReportsFinancialRoute
  '/reports/number-leases': typeof AppReportsNumberLeasesRoute
  '/products': typeof AppProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/barcodes': typeof AppBarcodesRoute
  '/_app/bonds': typeof AppBondsRoute
  '/_app/brands': typeof AppBrandsRoute
  '/_app/categories': typeof AppCategoriesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/locations': typeof AppLocationsRoute
  '/_app/pos': typeof AppPosRoute
  '/_app/sales': typeof AppSalesRoute
  '/_app/shifts': typeof AppShiftsRoute
  '/_app/skus': typeof AppSkusRoute
  '/_app/stock-ledger': typeof AppStockLedgerRoute
  '/_app/transfers': typeof AppTransfersRoute
  '/_app/units': typeof AppUnitsRoute
  '/_app/products/$productId': typeof AppProductsProductIdRoute
  '/_app/reports/financial': typeof AppReportsFinancialRoute
  '/_app/reports/number-leases': typeof AppReportsNumberLeasesRoute
  '/_app/products/': typeof AppProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/barcodes'
    | '/bonds'
    | '/brands'
    | '/categories'
    | '/dashboard'
    | '/inventory'
    | '/locations'
    | '/pos'
    | '/sales'
    | '/shifts'
    | '/skus'
    | '/stock-ledger'
    | '/transfers'
    | '/units'
    | '/products/$productId'
    | '/reports/financial'
    | '/reports/number-leases'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/barcodes'
    | '/bonds'
    | '/brands'
    | '/categories'
    | '/dashboard'
    | '/inventory'
    | '/locations'
    | '/pos'
    | '/sales'
    | '/shifts'
    | '/skus'
    | '/stock-ledger'
    | '/transfers'
    | '/units'
    | '/products/$productId'
    | '/reports/financial'
    | '/reports/number-leases'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/barcodes'
    | '/_app/bonds'
    | '/_app/brands'
    | '/_app/categories'
    | '/_app/dashboard'
    | '/_app/inventory'
    | '/_app/locations'
    | '/_app/pos'
    | '/_app/sales'
    | '/_app/shifts'
    | '/_app/skus'
    | '/_app/stock-ledger'
    | '/_app/transfers'
    | '/_app/units'
    | '/_app/products/$productId'
    | '/_app/reports/financial'
    | '/_app/reports/number-leases'
    | '/_app/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/units': {
      id: '/_app/units'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof AppUnitsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/transfers': {
      id: '/_app/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof AppTransfersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/stock-ledger': {
      id: '/_app/stock-ledger'
      path: '/stock-ledger'
      fullPath: '/stock-ledger'
      preLoaderRoute: typeof AppStockLedgerRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/skus': {
      id: '/_app/skus'
      path: '/skus'
      fullPath: '/skus'
      preLoaderRoute: typeof AppSkusRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/shifts': {
      id: '/_app/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof AppShiftsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/sales': {
      id: '/_app/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/pos': {
      id: '/_app/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AppPosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/locations': {
      id: '/_app/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof AppLocationsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/categories': {
      id: '/_app/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AppCategoriesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/brands': {
      id: '/_app/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof AppBrandsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/bonds': {
      id: '/_app/bonds'
      path: '/bonds'
      fullPath: '/bonds'
      preLoaderRoute: typeof AppBondsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/barcodes': {
      id: '/_app/barcodes'
      path: '/barcodes'
      fullPath: '/barcodes'
      preLoaderRoute: typeof AppBarcodesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/products/': {
      id: '/_app/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/reports/number-leases': {
      id: '/_app/reports/number-leases'
      path: '/reports/number-leases'
      fullPath: '/reports/number-leases'
      preLoaderRoute: typeof AppReportsNumberLeasesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/reports/financial': {
      id: '/_app/reports/financial'
      path: '/reports/financial'
      fullPath: '/reports/financial'
      preLoaderRoute: typeof AppReportsFinancialRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/products/$productId': {
      id: '/_app/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof AppProductsProductIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppBarcodesRoute: typeof AppBarcodesRoute
  AppBondsRoute: typeof AppBondsRoute
  AppBrandsRoute: typeof AppBrandsRoute
  AppCategoriesRoute: typeof AppCategoriesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppLocationsRoute: typeof AppLocationsRoute
  AppPosRoute: typeof AppPosRoute
  AppSalesRoute: typeof AppSalesRoute
  AppShiftsRoute: typeof AppShiftsRoute
  AppSkusRoute: typeof AppSkusRoute
  AppStockLedgerRoute: typeof AppStockLedgerRoute
  AppTransfersRoute: typeof AppTransfersRoute
  AppUnitsRoute: typeof AppUnitsRoute
  AppProductsProductIdRoute: typeof AppProductsProductIdRoute
  AppReportsFinancialRoute: typeof AppReportsFinancialRoute
  AppReportsNumberLeasesRoute: typeof AppReportsNumberLeasesRoute
  AppProductsIndexRoute: typeof AppProductsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppBarcodesRoute: AppBarcodesRoute,
  AppBondsRoute: AppBondsRoute,
  AppBrandsRoute: AppBrandsRoute,
  AppCategoriesRoute: AppCategoriesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppLocationsRoute: AppLocationsRoute,
  AppPosRoute: AppPosRoute,
  AppSalesRoute: AppSalesRoute,
  AppShiftsRoute: AppShiftsRoute,
  AppSkusRoute: AppSkusRoute,
  AppStockLedgerRoute: AppStockLedgerRoute,
  AppTransfersRoute: AppTransfersRoute,
  AppUnitsRoute: AppUnitsRoute,
  AppProductsProductIdRoute: AppProductsProductIdRoute,
  AppReportsFinancialRoute: AppReportsFinancialRoute,
  AppReportsNumberLeasesRoute: AppReportsNumberLeasesRoute,
  AppProductsIndexRoute: AppProductsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
