/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVariantsRouteImport } from './routes/_app/variants'
import { Route as AppUomConversionsRouteImport } from './routes/_app/uom-conversions'
import { Route as AppUnitsRouteImport } from './routes/_app/units'
import { Route as AppTransfersRouteImport } from './routes/_app/transfers'
import { Route as AppStockLedgerRouteImport } from './routes/_app/stock-ledger'
import { Route as AppSkusRouteImport } from './routes/_app/skus'
import { Route as AppShiftsRouteImport } from './routes/_app/shifts'
import { Route as AppSalesRouteImport } from './routes/_app/sales'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppProcurementRouteImport } from './routes/_app/procurement'
import { Route as AppPosRouteImport } from './routes/_app/pos'
import { Route as AppOperationsRouteImport } from './routes/_app/operations'
import { Route as AppLotsRouteImport } from './routes/_app/lots'
import { Route as AppLocationsRouteImport } from './routes/_app/locations'
import { Route as AppInventoryRouteImport } from './routes/_app/inventory'
import { Route as AppFinancialsRouteImport } from './routes/_app/financials'
import { Route as AppErrorMaintenanceRouteImport } from './routes/_app/error-maintenance'
import { Route as AppError500RouteImport } from './routes/_app/error-500'
import { Route as AppError404RouteImport } from './routes/_app/error-404'
import { Route as AppError403RouteImport } from './routes/_app/error-403'
import { Route as AppError401RouteImport } from './routes/_app/error-401'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCommerceRouteImport } from './routes/_app/commerce'
import { Route as AppCategoriesRouteImport } from './routes/_app/categories'
import { Route as AppBrandsRouteImport } from './routes/_app/brands'
import { Route as AppBondsRouteImport } from './routes/_app/bonds'
import { Route as AppBarcodesRouteImport } from './routes/_app/barcodes'
import { Route as AppProductsIndexRouteImport } from './routes/_app/products.index'
import { Route as AppReportsNumberLeasesRouteImport } from './routes/_app/reports.number-leases'
import { Route as AppReportsFinancialRouteImport } from './routes/_app/reports.financial'
import { Route as AppProductsProductIdRouteImport } from './routes/_app/products.$productId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVariantsRoute = AppVariantsRouteImport.update({
  id: '/variants',
  path: '/variants',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUomConversionsRoute = AppUomConversionsRouteImport.update({
  id: '/uom-conversions',
  path: '/uom-conversions',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUnitsRoute = AppUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTransfersRoute = AppTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppStockLedgerRoute = AppStockLedgerRouteImport.update({
  id: '/stock-ledger',
  path: '/stock-ledger',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSkusRoute = AppSkusRouteImport.update({
  id: '/skus',
  path: '/skus',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppShiftsRoute = AppShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProcurementRoute = AppProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPosRoute = AppPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOperationsRoute = AppOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLotsRoute = AppLotsRouteImport.update({
  id: '/lots',
  path: '/lots',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLocationsRoute = AppLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFinancialsRoute = AppFinancialsRouteImport.update({
  id: '/financials',
  path: '/financials',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppErrorMaintenanceRoute = AppErrorMaintenanceRouteImport.update({
  id: '/error-maintenance',
  path: '/error-maintenance',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppError500Route = AppError500RouteImport.update({
  id: '/error-500',
  path: '/error-500',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppError404Route = AppError404RouteImport.update({
  id: '/error-404',
  path: '/error-404',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppError403Route = AppError403RouteImport.update({
  id: '/error-403',
  path: '/error-403',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppError401Route = AppError401RouteImport.update({
  id: '/error-401',
  path: '/error-401',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCommerceRoute = AppCommerceRouteImport.update({
  id: '/commerce',
  path: '/commerce',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCategoriesRoute = AppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBrandsRoute = AppBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBondsRoute = AppBondsRouteImport.update({
  id: '/bonds',
  path: '/bonds',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBarcodesRoute = AppBarcodesRouteImport.update({
  id: '/barcodes',
  path: '/barcodes',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReportsNumberLeasesRoute = AppReportsNumberLeasesRouteImport.update({
  id: '/number-leases',
  path: '/number-leases',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsFinancialRoute = AppReportsFinancialRouteImport.update({
  id: '/financial',
  path: '/financial',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppProductsProductIdRoute = AppProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/barcodes': typeof AppBarcodesRoute
  '/bonds': typeof AppBondsRoute
  '/brands': typeof AppBrandsRoute
  '/categories': typeof AppCategoriesRoute
  '/commerce': typeof AppCommerceRoute
  '/dashboard': typeof AppDashboardRoute
  '/error-401': typeof AppError401Route
  '/error-403': typeof AppError403Route
  '/error-404': typeof AppError404Route
  '/error-500': typeof AppError500Route
  '/error-maintenance': typeof AppErrorMaintenanceRoute
  '/financials': typeof AppFinancialsRoute
  '/inventory': typeof AppInventoryRoute
  '/locations': typeof AppLocationsRoute
  '/lots': typeof AppLotsRoute
  '/operations': typeof AppOperationsRoute
  '/pos': typeof AppPosRoute
  '/procurement': typeof AppProcurementRoute
  '/reports': typeof AppReportsRouteWithChildren
  '/sales': typeof AppSalesRoute
  '/shifts': typeof AppShiftsRoute
  '/skus': typeof AppSkusRoute
  '/stock-ledger': typeof AppStockLedgerRoute
  '/transfers': typeof AppTransfersRoute
  '/units': typeof AppUnitsRoute
  '/uom-conversions': typeof AppUomConversionsRoute
  '/variants': typeof AppVariantsRoute
  '/products/$productId': typeof AppProductsProductIdRoute
  '/reports/financial': typeof AppReportsFinancialRoute
  '/reports/number-leases': typeof AppReportsNumberLeasesRoute
  '/products/': typeof AppProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/barcodes': typeof AppBarcodesRoute
  '/bonds': typeof AppBondsRoute
  '/brands': typeof AppBrandsRoute
  '/categories': typeof AppCategoriesRoute
  '/commerce': typeof AppCommerceRoute
  '/dashboard': typeof AppDashboardRoute
  '/error-401': typeof AppError401Route
  '/error-403': typeof AppError403Route
  '/error-404': typeof AppError404Route
  '/error-500': typeof AppError500Route
  '/error-maintenance': typeof AppErrorMaintenanceRoute
  '/financials': typeof AppFinancialsRoute
  '/inventory': typeof AppInventoryRoute
  '/locations': typeof AppLocationsRoute
  '/lots': typeof AppLotsRoute
  '/operations': typeof AppOperationsRoute
  '/pos': typeof AppPosRoute
  '/procurement': typeof AppProcurementRoute
  '/reports': typeof AppReportsRouteWithChildren
  '/sales': typeof AppSalesRoute
  '/shifts': typeof AppShiftsRoute
  '/skus': typeof AppSkusRoute
  '/stock-ledger': typeof AppStockLedgerRoute
  '/transfers': typeof AppTransfersRoute
  '/units': typeof AppUnitsRoute
  '/uom-conversions': typeof AppUomConversionsRoute
  '/variants': typeof AppVariantsRoute
  '/products/$productId': typeof AppProductsProductIdRoute
  '/reports/financial': typeof AppReportsFinancialRoute
  '/reports/number-leases': typeof AppReportsNumberLeasesRoute
  '/products': typeof AppProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/barcodes': typeof AppBarcodesRoute
  '/_app/bonds': typeof AppBondsRoute
  '/_app/brands': typeof AppBrandsRoute
  '/_app/categories': typeof AppCategoriesRoute
  '/_app/commerce': typeof AppCommerceRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/error-401': typeof AppError401Route
  '/_app/error-403': typeof AppError403Route
  '/_app/error-404': typeof AppError404Route
  '/_app/error-500': typeof AppError500Route
  '/_app/error-maintenance': typeof AppErrorMaintenanceRoute
  '/_app/financials': typeof AppFinancialsRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/locations': typeof AppLocationsRoute
  '/_app/lots': typeof AppLotsRoute
  '/_app/operations': typeof AppOperationsRoute
  '/_app/pos': typeof AppPosRoute
  '/_app/procurement': typeof AppProcurementRoute
  '/_app/reports': typeof AppReportsRouteWithChildren
  '/_app/sales': typeof AppSalesRoute
  '/_app/shifts': typeof AppShiftsRoute
  '/_app/skus': typeof AppSkusRoute
  '/_app/stock-ledger': typeof AppStockLedgerRoute
  '/_app/transfers': typeof AppTransfersRoute
  '/_app/units': typeof AppUnitsRoute
  '/_app/uom-conversions': typeof AppUomConversionsRoute
  '/_app/variants': typeof AppVariantsRoute
  '/_app/products/$productId': typeof AppProductsProductIdRoute
  '/_app/reports/financial': typeof AppReportsFinancialRoute
  '/_app/reports/number-leases': typeof AppReportsNumberLeasesRoute
  '/_app/products/': typeof AppProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/barcodes'
    | '/bonds'
    | '/brands'
    | '/categories'
    | '/commerce'
    | '/dashboard'
    | '/error-401'
    | '/error-403'
    | '/error-404'
    | '/error-500'
    | '/error-maintenance'
    | '/financials'
    | '/inventory'
    | '/locations'
    | '/lots'
    | '/operations'
    | '/pos'
    | '/procurement'
    | '/reports'
    | '/sales'
    | '/shifts'
    | '/skus'
    | '/stock-ledger'
    | '/transfers'
    | '/units'
    | '/uom-conversions'
    | '/variants'
    | '/products/$productId'
    | '/reports/financial'
    | '/reports/number-leases'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/barcodes'
    | '/bonds'
    | '/brands'
    | '/categories'
    | '/commerce'
    | '/dashboard'
    | '/error-401'
    | '/error-403'
    | '/error-404'
    | '/error-500'
    | '/error-maintenance'
    | '/financials'
    | '/inventory'
    | '/locations'
    | '/lots'
    | '/operations'
    | '/pos'
    | '/procurement'
    | '/reports'
    | '/sales'
    | '/shifts'
    | '/skus'
    | '/stock-ledger'
    | '/transfers'
    | '/units'
    | '/uom-conversions'
    | '/variants'
    | '/products/$productId'
    | '/reports/financial'
    | '/reports/number-leases'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/barcodes'
    | '/_app/bonds'
    | '/_app/brands'
    | '/_app/categories'
    | '/_app/commerce'
    | '/_app/dashboard'
    | '/_app/error-401'
    | '/_app/error-403'
    | '/_app/error-404'
    | '/_app/error-500'
    | '/_app/error-maintenance'
    | '/_app/financials'
    | '/_app/inventory'
    | '/_app/locations'
    | '/_app/lots'
    | '/_app/operations'
    | '/_app/pos'
    | '/_app/procurement'
    | '/_app/reports'
    | '/_app/sales'
    | '/_app/shifts'
    | '/_app/skus'
    | '/_app/stock-ledger'
    | '/_app/transfers'
    | '/_app/units'
    | '/_app/uom-conversions'
    | '/_app/variants'
    | '/_app/products/$productId'
    | '/_app/reports/financial'
    | '/_app/reports/number-leases'
    | '/_app/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/variants': {
      id: '/_app/variants'
      path: '/variants'
      fullPath: '/variants'
      preLoaderRoute: typeof AppVariantsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/uom-conversions': {
      id: '/_app/uom-conversions'
      path: '/uom-conversions'
      fullPath: '/uom-conversions'
      preLoaderRoute: typeof AppUomConversionsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/units': {
      id: '/_app/units'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof AppUnitsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/transfers': {
      id: '/_app/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof AppTransfersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/stock-ledger': {
      id: '/_app/stock-ledger'
      path: '/stock-ledger'
      fullPath: '/stock-ledger'
      preLoaderRoute: typeof AppStockLedgerRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/skus': {
      id: '/_app/skus'
      path: '/skus'
      fullPath: '/skus'
      preLoaderRoute: typeof AppSkusRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/shifts': {
      id: '/_app/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof AppShiftsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/sales': {
      id: '/_app/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/procurement': {
      id: '/_app/procurement'
      path: '/procurement'
      fullPath: '/procurement'
      preLoaderRoute: typeof AppProcurementRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/pos': {
      id: '/_app/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AppPosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/operations': {
      id: '/_app/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof AppOperationsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/lots': {
      id: '/_app/lots'
      path: '/lots'
      fullPath: '/lots'
      preLoaderRoute: typeof AppLotsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/locations': {
      id: '/_app/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof AppLocationsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/financials': {
      id: '/_app/financials'
      path: '/financials'
      fullPath: '/financials'
      preLoaderRoute: typeof AppFinancialsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/error-maintenance': {
      id: '/_app/error-maintenance'
      path: '/error-maintenance'
      fullPath: '/error-maintenance'
      preLoaderRoute: typeof AppErrorMaintenanceRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/error-500': {
      id: '/_app/error-500'
      path: '/error-500'
      fullPath: '/error-500'
      preLoaderRoute: typeof AppError500RouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/error-404': {
      id: '/_app/error-404'
      path: '/error-404'
      fullPath: '/error-404'
      preLoaderRoute: typeof AppError404RouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/error-403': {
      id: '/_app/error-403'
      path: '/error-403'
      fullPath: '/error-403'
      preLoaderRoute: typeof AppError403RouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/error-401': {
      id: '/_app/error-401'
      path: '/error-401'
      fullPath: '/error-401'
      preLoaderRoute: typeof AppError401RouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/commerce': {
      id: '/_app/commerce'
      path: '/commerce'
      fullPath: '/commerce'
      preLoaderRoute: typeof AppCommerceRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/categories': {
      id: '/_app/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AppCategoriesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/brands': {
      id: '/_app/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof AppBrandsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/bonds': {
      id: '/_app/bonds'
      path: '/bonds'
      fullPath: '/bonds'
      preLoaderRoute: typeof AppBondsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/barcodes': {
      id: '/_app/barcodes'
      path: '/barcodes'
      fullPath: '/barcodes'
      preLoaderRoute: typeof AppBarcodesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/products/': {
      id: '/_app/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/reports/number-leases': {
      id: '/_app/reports/number-leases'
      path: '/number-leases'
      fullPath: '/reports/number-leases'
      preLoaderRoute: typeof AppReportsNumberLeasesRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/_app/reports/financial': {
      id: '/_app/reports/financial'
      path: '/financial'
      fullPath: '/reports/financial'
      preLoaderRoute: typeof AppReportsFinancialRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/_app/products/$productId': {
      id: '/_app/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof AppProductsProductIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppReportsRouteChildren {
  AppReportsFinancialRoute: typeof AppReportsFinancialRoute
  AppReportsNumberLeasesRoute: typeof AppReportsNumberLeasesRoute
}

const AppReportsRouteChildren: AppReportsRouteChildren = {
  AppReportsFinancialRoute: AppReportsFinancialRoute,
  AppReportsNumberLeasesRoute: AppReportsNumberLeasesRoute,
}

const AppReportsRouteWithChildren = AppReportsRoute._addFileChildren(
  AppReportsRouteChildren,
)

interface AppRouteRouteChildren {
  AppBarcodesRoute: typeof AppBarcodesRoute
  AppBondsRoute: typeof AppBondsRoute
  AppBrandsRoute: typeof AppBrandsRoute
  AppCategoriesRoute: typeof AppCategoriesRoute
  AppCommerceRoute: typeof AppCommerceRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppError401Route: typeof AppError401Route
  AppError403Route: typeof AppError403Route
  AppError404Route: typeof AppError404Route
  AppError500Route: typeof AppError500Route
  AppErrorMaintenanceRoute: typeof AppErrorMaintenanceRoute
  AppFinancialsRoute: typeof AppFinancialsRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppLocationsRoute: typeof AppLocationsRoute
  AppLotsRoute: typeof AppLotsRoute
  AppOperationsRoute: typeof AppOperationsRoute
  AppPosRoute: typeof AppPosRoute
  AppProcurementRoute: typeof AppProcurementRoute
  AppReportsRoute: typeof AppReportsRouteWithChildren
  AppSalesRoute: typeof AppSalesRoute
  AppShiftsRoute: typeof AppShiftsRoute
  AppSkusRoute: typeof AppSkusRoute
  AppStockLedgerRoute: typeof AppStockLedgerRoute
  AppTransfersRoute: typeof AppTransfersRoute
  AppUnitsRoute: typeof AppUnitsRoute
  AppUomConversionsRoute: typeof AppUomConversionsRoute
  AppVariantsRoute: typeof AppVariantsRoute
  AppProductsProductIdRoute: typeof AppProductsProductIdRoute
  AppProductsIndexRoute: typeof AppProductsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppBarcodesRoute: AppBarcodesRoute,
  AppBondsRoute: AppBondsRoute,
  AppBrandsRoute: AppBrandsRoute,
  AppCategoriesRoute: AppCategoriesRoute,
  AppCommerceRoute: AppCommerceRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppError401Route: AppError401Route,
  AppError403Route: AppError403Route,
  AppError404Route: AppError404Route,
  AppError500Route: AppError500Route,
  AppErrorMaintenanceRoute: AppErrorMaintenanceRoute,
  AppFinancialsRoute: AppFinancialsRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppLocationsRoute: AppLocationsRoute,
  AppLotsRoute: AppLotsRoute,
  AppOperationsRoute: AppOperationsRoute,
  AppPosRoute: AppPosRoute,
  AppProcurementRoute: AppProcurementRoute,
  AppReportsRoute: AppReportsRouteWithChildren,
  AppSalesRoute: AppSalesRoute,
  AppShiftsRoute: AppShiftsRoute,
  AppSkusRoute: AppSkusRoute,
  AppStockLedgerRoute: AppStockLedgerRoute,
  AppTransfersRoute: AppTransfersRoute,
  AppUnitsRoute: AppUnitsRoute,
  AppUomConversionsRoute: AppUomConversionsRoute,
  AppVariantsRoute: AppVariantsRoute,
  AppProductsProductIdRoute: AppProductsProductIdRoute,
  AppProductsIndexRoute: AppProductsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
