// Sample CRM directory for RetailOS — Caribbean retail (Guyana, GYD/USD).
// Customers, wholesale accounts, and suppliers. Phone numbers are 10 digits
// (592 country code + 7 local digits) to satisfy the 10-digit validation while
// staying on-theme. No backend wiring — this seeds the in-memory zustand store.
import type { Contact } from "@/features/contacts/types";

export const db: Contact[] = [
  {
    firstName: "Anita",
    lastName: "Persaud",
    image: "/images/avatars/avatar-1.webp",
    email: "anita.persaud@bourdafresh.gy",
    phone: 5_926_891_204,
    city: "Georgetown",
    company: "Bourda Fresh Market",
    creditLimitGyd: 1_500_000,
    loyaltyTier: "Gold",
    lastPurchase: "Wholesale rice — 40 bags",
    notes:
      "Wholesale grocery account. Settles on 30-day terms, always on time.",
    addedDate: new Date("2025-11-02"),
    labels: ["wholesale", "customer"],
    status: "active",
    isFavourite: true,
    isRecent: true,
    isBlocked: false,
    isSpam: false,
  },
  {
    firstName: "Marcus",
    lastName: "Bourne",
    image: "/images/avatars/avatar-2.webp",
    email: "marcus@bournehardware.gy",
    phone: 5_926_225_518,
    city: "New Amsterdam",
    company: "Bourne Hardware Ltd",
    creditLimitGyd: 800_000,
    loyaltyTier: "Silver",
    lastPurchase: "Cement & rebar restock",
    notes: "Hardware retailer in Berbice. Prefers WhatsApp for order confirms.",
    addedDate: new Date("2025-10-18"),
    labels: ["customer", "partner"],
    status: "active",
    isFavourite: true,
    isRecent: false,
    isBlocked: false,
    isSpam: false,
  },
  {
    firstName: "Ramnarine",
    lastName: "Singh",
    image: "/images/avatars/avatar-3.webp",
    email: "sales@ramnarinedistributors.gy",
    phone: 5_926_014_477,
    city: "Parika",
    company: "Ramnarine Distributors",
    creditLimitGyd: 3_200_000,
    loyaltyTier: "Platinum",
    lastPurchase: "Mixed dry goods container",
    notes: "Primary FMCG supplier. Imports via Georgetown wharf monthly.",
    addedDate: new Date("2025-09-30"),
    labels: ["supplier"],
    status: "active",
    isFavourite: false,
    isRecent: true,
    isBlocked: false,
    isSpam: false,
  },
  {
    firstName: "Cheryl",
    lastName: "Adams",
    image: "/images/avatars/avatar-4.webp",
    email: "cheryl.adams@gmail.com",
    phone: 5_926_773_390,
    city: "Linden",
    company: "Walk-in",
    loyaltyTier: "Bronze",
    lastPurchase: "Household electronics",
    notes: "Loyal retail customer. Shops every payday weekend.",
    addedDate: new Date("2026-01-12"),
    labels: ["customer"],
    status: "active",
    isFavourite: false,
    isRecent: true,
    isBlocked: false,
    isSpam: false,
  },
  {
    firstName: "Desmond",
    lastName: "Fraser",
    image: "/images/avatars/avatar-5.webp",
    email: "desmond.fraser@frasersautoparts.gy",
    phone: 5_926_459_911,
    city: "Georgetown",
    company: "Fraser's Auto Parts",
    creditLimitGyd: 1_100_000,
    loyaltyTier: "Gold",
    lastPurchase: "Brake & filter assortment",
    notes:
      "Auto parts reseller. Interested in opening a second branch account.",
    addedDate: new Date("2025-12-05"),
    labels: ["customer", "vip"],
    status: "active",
    isFavourite: false,
    isRecent: false,
    isBlocked: false,
    isSpam: false,
  },
  {
    firstName: "Priya",
    lastName: "Mohabir",
    image: "/images/avatars/avatar-6.webp",
    email: "priya@mohabirpharmacy.gy",
    phone: 5_926_338_820,
    city: "Anna Regina",
    company: "Mohabir Pharmacy",
    creditLimitGyd: 950_000,
    loyaltyTier: "Silver",
    lastPurchase: "OTC & first-aid restock",
    notes: "Pharmacy on the Essequibo coast. Needs FEFO batch tracking.",
    addedDate: new Date("2025-11-22"),
    labels: ["customer", "wholesale"],
    status: "active",
    isFavourite: true,
    isRecent: true,
    isBlocked: false,
    isSpam: false,
  },
  {
    firstName: "Leon",
    lastName: "Trotman",
    image: "/images/avatars/avatar-7.webp",
    email: "leon.trotman@outlook.com",
    phone: 5_926_902_255,
    city: "Bartica",
    company: "Walk-in",
    loyaltyTier: "Bronze",
    lastPurchase: "Generator & fuel cans",
    notes: "Mining-camp supplier. Buys in bulk before river trips.",
    addedDate: new Date("2026-02-01"),
    labels: ["lead"],
    status: "prospect",
    isFavourite: false,
    isRecent: true,
    isBlocked: false,
    isSpam: false,
  },
  {
    firstName: "Natasha",
    lastName: "Williams",
    image: "/images/avatars/avatar-8.webp",
    email: "natasha@williamsboutique.gy",
    phone: 5_926_147_733,
    city: "Georgetown",
    company: "Williams Boutique",
    creditLimitGyd: 400_000,
    loyaltyTier: "Silver",
    lastPurchase: "Apparel seasonal order",
    notes: "Clothing retailer. Strong online cross-sell potential.",
    addedDate: new Date("2025-12-19"),
    labels: ["customer", "partner"],
    status: "active",
    isFavourite: false,
    isRecent: false,
    isBlocked: false,
    isSpam: false,
  },
  {
    firstName: "Imran",
    lastName: "Khan",
    image: "/images/avatars/avatar-9.webp",
    email: "imran@khanwholesale.gy",
    phone: 5_926_581_044,
    city: "Corriverton",
    company: "Khan Wholesale",
    creditLimitGyd: 2_400_000,
    loyaltyTier: "Platinum",
    lastPurchase: "Beverage pallet — 60 cases",
    notes: "High-volume wholesale buyer near the Suriname border.",
    addedDate: new Date("2025-10-04"),
    labels: ["wholesale", "vip"],
    status: "active",
    isFavourite: true,
    isRecent: false,
    isBlocked: false,
    isSpam: false,
  },
  {
    firstName: "Gail",
    lastName: "Henry",
    image: "/images/avatars/avatar-10.webp",
    email: "gail.henry@henrygrocery.gy",
    phone: 5_926_720_098,
    city: "Mahaica",
    company: "Henry's Grocery",
    creditLimitGyd: 350_000,
    loyaltyTier: "Bronze",
    lastPurchase: "Weekly grocery restock",
    notes: "Village mini-mart. Considers Edge Hub for unstable internet.",
    addedDate: new Date("2026-01-28"),
    labels: ["customer"],
    status: "active",
    isFavourite: false,
    isRecent: true,
    isBlocked: false,
    isSpam: false,
  },
  {
    firstName: "Vishal",
    lastName: "Ramkissoon",
    image: "/images/avatars/avatar-11.webp",
    email: "vishal@ramkissoonimports.gy",
    phone: 5_926_305_571,
    city: "Georgetown",
    company: "Ramkissoon Imports",
    creditLimitGyd: 5_000_000,
    loyaltyTier: "Platinum",
    lastPurchase: "Bonded electronics shipment",
    notes: "Import/export partner. Handles bonded warehouse clearances.",
    addedDate: new Date("2025-08-15"),
    labels: ["supplier", "partner"],
    status: "active",
    isFavourite: false,
    isRecent: false,
    isBlocked: false,
    isSpam: false,
  },
  {
    firstName: "Sandra",
    lastName: "Profitt",
    image: "/images/avatars/avatar-12.webp",
    email: "sandra.profitt@gmail.com",
    phone: 5_926_889_912,
    city: "Rose Hall",
    company: "Walk-in",
    loyaltyTier: "Bronze",
    lastPurchase: "Furniture layaway deposit",
    notes: "Furniture customer on a layaway plan. Two payments remaining.",
    addedDate: new Date("2026-02-10"),
    labels: ["customer"],
    status: "active",
    isFavourite: false,
    isRecent: true,
    isBlocked: false,
    isSpam: false,
  },
  {
    firstName: "Trevor",
    lastName: "Da Silva",
    image: "/images/avatars/avatar-13.webp",
    email: "trevor@dasilvafarms.gy",
    phone: 5_926_410_263,
    city: "Lethem",
    company: "Da Silva Farms",
    creditLimitGyd: 700_000,
    loyaltyTier: "Silver",
    lastPurchase: "Agricultural tools order",
    notes: "Rupununi supplier of fresh produce. Cross-border logistics.",
    addedDate: new Date("2025-11-11"),
    labels: ["supplier", "lead"],
    status: "prospect",
    isFavourite: false,
    isRecent: false,
    isBlocked: false,
    isSpam: false,
  },
  {
    firstName: "Onika",
    lastName: "Caesar",
    image: "/images/avatars/avatar-14.webp",
    email: "onika.caesar@caesarcosmetics.gy",
    phone: 5_926_556_640,
    city: "Georgetown",
    company: "Caesar Cosmetics",
    creditLimitGyd: 600_000,
    loyaltyTier: "Gold",
    lastPurchase: "Beauty supplies bundle",
    notes: "Cosmetics retailer. VIP — strong repeat-purchase pattern.",
    addedDate: new Date("2025-12-29"),
    labels: ["vip", "customer"],
    status: "active",
    isFavourite: true,
    isRecent: true,
    isBlocked: false,
    isSpam: false,
  },
  {
    firstName: "Brian",
    lastName: "Lall",
    image: "/images/avatars/avatar-15.webp",
    email: "brian.lall@lallelectrical.gy",
    phone: 5_926_033_188,
    city: "Diamond",
    company: "Lall Electrical",
    creditLimitGyd: 1_300_000,
    loyaltyTier: "Gold",
    lastPurchase: "Wiring & breaker stock",
    notes: "Electrical wholesaler on the East Bank. Reliable partner.",
    addedDate: new Date("2025-10-25"),
    labels: ["wholesale", "partner"],
    status: "active",
    isFavourite: false,
    isRecent: false,
    isBlocked: false,
    isSpam: false,
  },
  {
    firstName: "Yvonne",
    lastName: "Beharry",
    image: "/images/avatars/avatar-16.webp",
    email: "yvonne.beharry@gmail.com",
    phone: 5_926_744_521,
    city: "Vreed-en-Hoop",
    company: "Walk-in",
    loyaltyTier: "Bronze",
    lastPurchase: "School supplies bulk",
    notes: "Seasonal back-to-school buyer. Prospect for a loyalty card.",
    addedDate: new Date("2026-01-05"),
    labels: ["lead"],
    status: "prospect",
    isFavourite: false,
    isRecent: false,
    isBlocked: false,
    isSpam: false,
  },
  {
    firstName: "Kwame",
    lastName: "Edwards",
    image: "/images/avatars/avatar-17.webp",
    email: "kwame.deals@quickmoney.example",
    phone: 5_926_990_001,
    city: "Unknown",
    company: "Unverified",
    notes:
      "Flagged: pushy unsolicited 'distributor' offers. Verify before trade.",
    addedDate: new Date("2026-02-14"),
    labels: ["lead"],
    status: "inactive",
    isFavourite: false,
    isRecent: false,
    isBlocked: false,
    isSpam: true,
  },
  {
    firstName: "Errol",
    lastName: "Babb",
    image: "/images/avatars/avatar-18.webp",
    email: "errol.babb@example.com",
    phone: 5_926_118_876,
    city: "Georgetown",
    company: "Babb Trading",
    notes: "Blocked: chargeback disputes and bounced cheques on file.",
    addedDate: new Date("2025-09-08"),
    labels: ["customer"],
    status: "inactive",
    isFavourite: false,
    isRecent: false,
    isBlocked: true,
    isSpam: false,
  },
];
