// Retail mock data for the RetailOS datatable showcase.
// Money is shown in Guyana Dollars (GYD); quantities are whole units.

export type ProductCategory =
  | "beverages"
  | "grocery"
  | "hardware"
  | "electronics"
  | "pharmacy"
  | "apparel"
  | "household";

export interface ProductItem {
  barcode: string;
  brand: string;
  category: ProductCategory;
  costGyd: number;
  id: string;
  product: string;
  reorderLevel: number;
  sku: string;
  status: "published" | "draft" | "archived";
  stock: number;
}

export interface SaleItem {
  customer: string;
  fallback: string;
  id: string;
  payment: "cash" | "card" | "bank-transfer" | "mobile-money";
  reference: string;
  status: "completed" | "refunded" | "void";
  store: string;
  totalGyd: number;
}

export interface SupplierInvoiceItem {
  balanceGyd: number;
  category: string;
  fallback: string;
  id: string;
  issuedDate: Date;
  reference: string;
  status: "paid" | "partial" | "draft" | "overdue";
  supplier: string;
  totalGyd: number;
}

export type StaffRole =
  | "owner"
  | "manager"
  | "cashier"
  | "stock-clerk"
  | "accountant";

export interface StaffItem {
  email: string;
  fallback: string;
  id: string;
  role: StaffRole;
  staff: string;
  status: "active" | "inactive" | "invited";
  store: "Georgetown" | "Linden" | "Berbice" | "Bartica";
}

export const formatGyd = (value: number) =>
  `G$${new Intl.NumberFormat("en-GY", { maximumFractionDigits: 0 }).format(value)}`;

export const productData: ProductItem[] = [
  {
    id: "1",
    sku: "BEV-COKE-355",
    barcode: "7894900011517",
    product: "Coca-Cola 355ml Can",
    brand: "Coca-Cola",
    category: "beverages",
    costGyd: 180,
    stock: 1240,
    reorderLevel: 200,
    status: "published",
  },
  {
    id: "2",
    sku: "GRO-RICE-5KG",
    barcode: "8901030865278",
    product: "Karibee Parboiled Rice 5kg",
    brand: "Karibee",
    category: "grocery",
    costGyd: 2100,
    stock: 86,
    reorderLevel: 40,
    status: "published",
  },
  {
    id: "3",
    sku: "HW-NAIL-2IN",
    barcode: "0049000028911",
    product: 'Galvanised Nails 2" (1lb)',
    brand: "BuildRite",
    category: "hardware",
    costGyd: 540,
    stock: 18,
    reorderLevel: 25,
    status: "published",
  },
  {
    id: "4",
    sku: "ELE-EARB-PRO",
    barcode: "6921168550012",
    product: "Wireless Earbuds Pro",
    brand: "Oraimo",
    category: "electronics",
    costGyd: 9800,
    stock: 42,
    reorderLevel: 15,
    status: "published",
  },
  {
    id: "5",
    sku: "PHA-PARA-500",
    barcode: "5000158062337",
    product: "Paracetamol 500mg (24s)",
    brand: "Panadol",
    category: "pharmacy",
    costGyd: 760,
    stock: 9,
    reorderLevel: 30,
    status: "published",
  },
  {
    id: "6",
    sku: "APP-TSHIRT-M",
    barcode: "1903210004471",
    product: "Cotton Crew T-Shirt (M)",
    brand: "Caribbean Threads",
    category: "apparel",
    costGyd: 1450,
    stock: 0,
    reorderLevel: 20,
    status: "draft",
  },
  {
    id: "7",
    sku: "HH-DETER-2L",
    barcode: "7501035910478",
    product: "Liquid Detergent 2L",
    brand: "Sunlight",
    category: "household",
    costGyd: 1320,
    stock: 210,
    reorderLevel: 60,
    status: "published",
  },
  {
    id: "8",
    sku: "BEV-WATER-1L",
    barcode: "7894900700015",
    product: "Spring Water 1L",
    brand: "Aqua Mist",
    category: "beverages",
    costGyd: 220,
    stock: 540,
    reorderLevel: 150,
    status: "published",
  },
  {
    id: "9",
    sku: "GRO-FLOUR-2KG",
    barcode: "8712100849015",
    product: "All-Purpose Flour 2kg",
    brand: "Maid Marian",
    category: "grocery",
    costGyd: 980,
    stock: 64,
    reorderLevel: 40,
    status: "published",
  },
  {
    id: "10",
    sku: "ELE-PWR-10K",
    barcode: "6921168559015",
    product: "Power Bank 10000mAh",
    brand: "Oraimo",
    category: "electronics",
    costGyd: 6400,
    stock: 27,
    reorderLevel: 12,
    status: "published",
  },
  {
    id: "11",
    sku: "HW-PAINT-1G",
    barcode: "0049000044211",
    product: "Emulsion Paint 1 Gallon",
    brand: "Berger",
    category: "hardware",
    costGyd: 8200,
    stock: 31,
    reorderLevel: 10,
    status: "published",
  },
  {
    id: "12",
    sku: "PHA-VITC-1000",
    barcode: "5000158099012",
    product: "Vitamin C 1000mg (30s)",
    brand: "Redoxon",
    category: "pharmacy",
    costGyd: 1850,
    stock: 14,
    reorderLevel: 20,
    status: "published",
  },
  {
    id: "13",
    sku: "APP-CAP-ADJ",
    barcode: "1903210099017",
    product: "Adjustable Baseball Cap",
    brand: "Caribbean Threads",
    category: "apparel",
    costGyd: 1100,
    stock: 73,
    reorderLevel: 25,
    status: "archived",
  },
  {
    id: "14",
    sku: "HH-BLEACH-1L",
    barcode: "7501035919013",
    product: "Household Bleach 1L",
    brand: "Clorox",
    category: "household",
    costGyd: 640,
    stock: 188,
    reorderLevel: 50,
    status: "published",
  },
  {
    id: "15",
    sku: "BEV-JUICE-1L",
    barcode: "7894900722018",
    product: "Orange Juice 1L",
    brand: "Topco",
    category: "beverages",
    costGyd: 740,
    stock: 96,
    reorderLevel: 60,
    status: "published",
  },
  {
    id: "16",
    sku: "GRO-SUGAR-1KG",
    barcode: "8712100888014",
    product: "Brown Sugar 1kg",
    brand: "Demerara Gold",
    category: "grocery",
    costGyd: 420,
    stock: 7,
    reorderLevel: 80,
    status: "published",
  },
  {
    id: "17",
    sku: "ELE-BULB-LED",
    barcode: "6921168577011",
    product: "LED Bulb 9W (Pack of 4)",
    brand: "Philips",
    category: "electronics",
    costGyd: 2400,
    stock: 120,
    reorderLevel: 30,
    status: "published",
  },
  {
    id: "18",
    sku: "HW-TAPE-DUCT",
    barcode: "0049000077012",
    product: "Duct Tape 48mm x 25m",
    brand: "3M",
    category: "hardware",
    costGyd: 1280,
    stock: 54,
    reorderLevel: 20,
    status: "published",
  },
  {
    id: "19",
    sku: "PHA-IBU-200",
    barcode: "5000158033016",
    product: "Ibuprofen 200mg (20s)",
    brand: "Advil",
    category: "pharmacy",
    costGyd: 690,
    stock: 41,
    reorderLevel: 25,
    status: "published",
  },
  {
    id: "20",
    sku: "HH-TISSUE-12",
    barcode: "7501035944015",
    product: "Toilet Tissue (12 Rolls)",
    brand: "Soft & Gentle",
    category: "household",
    costGyd: 1980,
    stock: 145,
    reorderLevel: 40,
    status: "published",
  },
];

export const saleData: SaleItem[] = [
  {
    id: "1",
    reference: "POS-100245",
    customer: "Anita Persaud",
    fallback: "AP",
    store: "Georgetown",
    totalGyd: 14_600,
    payment: "cash",
    status: "completed",
  },
  {
    id: "2",
    reference: "POS-100246",
    customer: "Devon Williams",
    fallback: "DW",
    store: "Linden",
    totalGyd: 32_400,
    payment: "card",
    status: "completed",
  },
  {
    id: "3",
    reference: "POS-100247",
    customer: "Shanaz Khan",
    fallback: "SK",
    store: "Georgetown",
    totalGyd: 8200,
    payment: "mobile-money",
    status: "refunded",
  },
  {
    id: "4",
    reference: "POS-100248",
    customer: "Marlon Adams",
    fallback: "MA",
    store: "Berbice",
    totalGyd: 56_900,
    payment: "bank-transfer",
    status: "completed",
  },
  {
    id: "5",
    reference: "POS-100249",
    customer: "Priya Singh",
    fallback: "PS",
    store: "Georgetown",
    totalGyd: 4350,
    payment: "cash",
    status: "completed",
  },
  {
    id: "6",
    reference: "POS-100250",
    customer: "Errol Bacchus",
    fallback: "EB",
    store: "Bartica",
    totalGyd: 11_750,
    payment: "card",
    status: "void",
  },
  {
    id: "7",
    reference: "POS-100251",
    customer: "Natasha Lall",
    fallback: "NL",
    store: "Linden",
    totalGyd: 23_900,
    payment: "cash",
    status: "completed",
  },
  {
    id: "8",
    reference: "POS-100252",
    customer: "Trevor Gomes",
    fallback: "TG",
    store: "Georgetown",
    totalGyd: 7600,
    payment: "mobile-money",
    status: "completed",
  },
  {
    id: "9",
    reference: "POS-100253",
    customer: "Yasmin Ali",
    fallback: "YA",
    store: "Berbice",
    totalGyd: 18_200,
    payment: "card",
    status: "completed",
  },
  {
    id: "10",
    reference: "POS-100254",
    customer: "Colin Fraser",
    fallback: "CF",
    store: "Georgetown",
    totalGyd: 41_300,
    payment: "bank-transfer",
    status: "completed",
  },
  {
    id: "11",
    reference: "POS-100255",
    customer: "Hema Narine",
    fallback: "HN",
    store: "Linden",
    totalGyd: 9650,
    payment: "cash",
    status: "completed",
  },
  {
    id: "12",
    reference: "POS-100256",
    customer: "Brian Cummings",
    fallback: "BC",
    store: "Bartica",
    totalGyd: 5400,
    payment: "card",
    status: "refunded",
  },
];

export const supplierInvoiceData: SupplierInvoiceItem[] = [
  {
    id: "5099",
    reference: "SINV-5099",
    supplier: "Demerara Distributors",
    fallback: "DD",
    category: "Beverages",
    totalGyd: 312_000,
    balanceGyd: 0,
    issuedDate: new Date("2025-04-03"),
    status: "paid",
  },
  {
    id: "5008",
    reference: "SINV-5008",
    supplier: "Guyana Stores Wholesale",
    fallback: "GW",
    category: "Grocery",
    totalGyd: 145_000,
    balanceGyd: 45_000,
    issuedDate: new Date("2025-05-12"),
    status: "partial",
  },
  {
    id: "5101",
    reference: "SINV-5101",
    supplier: "Caribbean Hardware Co.",
    fallback: "CH",
    category: "Hardware",
    totalGyd: 120_000,
    balanceGyd: 0,
    issuedDate: new Date("2025-06-26"),
    status: "paid",
  },
  {
    id: "4586",
    reference: "SINV-4586",
    supplier: "Oraimo Caribbean",
    fallback: "OC",
    category: "Electronics",
    totalGyd: 268_000,
    balanceGyd: 268_000,
    issuedDate: new Date("2025-03-05"),
    status: "overdue",
  },
  {
    id: "4360",
    reference: "SINV-4360",
    supplier: "MedSupply Guyana",
    fallback: "MS",
    category: "Pharmacy",
    totalGyd: 96_000,
    balanceGyd: 0,
    issuedDate: new Date("2025-08-07"),
    status: "draft",
  },
  {
    id: "5104",
    reference: "SINV-5104",
    supplier: "Sunlight Distribution",
    fallback: "SD",
    category: "Household",
    totalGyd: 160_000,
    balanceGyd: 60_000,
    issuedDate: new Date("2025-08-26"),
    status: "partial",
  },
  {
    id: "5201",
    reference: "SINV-5201",
    supplier: "Berger Paints Guyana",
    fallback: "BP",
    category: "Hardware",
    totalGyd: 285_000,
    balanceGyd: 0,
    issuedDate: new Date("2025-01-15"),
    status: "paid",
  },
  {
    id: "4987",
    reference: "SINV-4987",
    supplier: "Demerara Distributors",
    fallback: "DD",
    category: "Beverages",
    totalGyd: 175_000,
    balanceGyd: 175_000,
    issuedDate: new Date("2025-02-20"),
    status: "overdue",
  },
  {
    id: "5342",
    reference: "SINV-5342",
    supplier: "Topco Foods",
    fallback: "TF",
    category: "Beverages",
    totalGyd: 350_000,
    balanceGyd: 120_000,
    issuedDate: new Date("2025-03-10"),
    status: "partial",
  },
  {
    id: "4723",
    reference: "SINV-4723",
    supplier: "Caribbean Threads Ltd",
    fallback: "CT",
    category: "Apparel",
    totalGyd: 220_000,
    balanceGyd: 0,
    issuedDate: new Date("2025-04-18"),
    status: "paid",
  },
  {
    id: "5445",
    reference: "SINV-5445",
    supplier: "Philips Lighting Agent",
    fallback: "PL",
    category: "Electronics",
    totalGyd: 420_000,
    balanceGyd: 0,
    issuedDate: new Date("2025-05-22"),
    status: "paid",
  },
  {
    id: "4892",
    reference: "SINV-4892",
    supplier: "Guyana Stores Wholesale",
    fallback: "GW",
    category: "Grocery",
    totalGyd: 195_000,
    balanceGyd: 95_000,
    issuedDate: new Date("2025-06-14"),
    status: "partial",
  },
  {
    id: "5667",
    reference: "SINV-5667",
    supplier: "MedSupply Guyana",
    fallback: "MS",
    category: "Pharmacy",
    totalGyd: 275_000,
    balanceGyd: 0,
    issuedDate: new Date("2025-07-08"),
    status: "paid",
  },
  {
    id: "4534",
    reference: "SINV-4534",
    supplier: "Clorox Distribution",
    fallback: "CD",
    category: "Household",
    totalGyd: 138_000,
    balanceGyd: 138_000,
    issuedDate: new Date("2025-01-28"),
    status: "overdue",
  },
];

export const staffData: StaffItem[] = [
  {
    id: "1",
    fallback: "AP",
    staff: "Anil Prashad",
    email: "anil.prashad@retailos.gy",
    role: "owner",
    store: "Georgetown",
    status: "active",
  },
  {
    id: "2",
    fallback: "SM",
    staff: "Samantha Moore",
    email: "samantha.moore@retailos.gy",
    role: "manager",
    store: "Georgetown",
    status: "active",
  },
  {
    id: "3",
    fallback: "RC",
    staff: "Rohan Chand",
    email: "rohan.chand@retailos.gy",
    role: "cashier",
    store: "Linden",
    status: "active",
  },
  {
    id: "4",
    fallback: "EW",
    staff: "Esther Wong",
    email: "esther.wong@retailos.gy",
    role: "accountant",
    store: "Georgetown",
    status: "invited",
  },
  {
    id: "5",
    fallback: "DG",
    staff: "Dale Grant",
    email: "dale.grant@retailos.gy",
    role: "stock-clerk",
    store: "Berbice",
    status: "active",
  },
  {
    id: "6",
    fallback: "LT",
    staff: "Lisa Thomas",
    email: "lisa.thomas@retailos.gy",
    role: "cashier",
    store: "Bartica",
    status: "inactive",
  },
  {
    id: "7",
    fallback: "MR",
    staff: "Marcus Roberts",
    email: "marcus.roberts@retailos.gy",
    role: "manager",
    store: "Linden",
    status: "active",
  },
  {
    id: "8",
    fallback: "JP",
    staff: "Jaya Persaud",
    email: "jaya.persaud@retailos.gy",
    role: "cashier",
    store: "Georgetown",
    status: "active",
  },
  {
    id: "9",
    fallback: "CB",
    staff: "Carl Benjamin",
    email: "carl.benjamin@retailos.gy",
    role: "stock-clerk",
    store: "Berbice",
    status: "inactive",
  },
  {
    id: "10",
    fallback: "AD",
    staff: "Amara Daniels",
    email: "amara.daniels@retailos.gy",
    role: "accountant",
    store: "Georgetown",
    status: "active",
  },
  {
    id: "11",
    fallback: "JJ",
    staff: "Jamal James",
    email: "jamal.james@retailos.gy",
    role: "cashier",
    store: "Bartica",
    status: "invited",
  },
  {
    id: "12",
    fallback: "MW",
    staff: "Maya Williams",
    email: "maya.williams@retailos.gy",
    role: "manager",
    store: "Berbice",
    status: "active",
  },
];
