// Shared human labels for route paths, keyed by full path OR last segment.
// One registry so the sidebar, command palette, and breadcrumbs all name a
// destination identically (design law: consistent naming across surfaces).
export const ROUTE_LABELS: Record<string, string> = {
  "/dashboard": "Dashboard",
  "/operations": "Operations",
  "/pos": "Point of Sale",
  "/sales": "Orders & Receipts",
  "/customers": "Customers",
  "/pricing": "Price Lists",
  "/promotions": "Promotions",
  "/shifts": "Shifts & Cash",
  "/products": "Products",
  "/categories": "Categories",
  "/brands": "Brands",
  "/units": "Units & Conversions",
  "/inventory": "Stock on Hand",
  "/stock-ledger": "Stock Ledger",
  "/adjustments": "Adjustments & Counts",
  "/transfers": "Transfers",
  "/lots": "Lots & Expiry",
  "/locations": "Locations",
  "/bonds": "Bonded Goods",
  "/suppliers": "Suppliers",
  "/procurement": "Purchase Orders",
  "/financials": "Accounting",
  "/receivables": "Receivables",
  "/payables": "Payables",
  "/commerce": "Online Store",
  "/reports": "Reports",
  "/notifications": "Notifications",
  "/staff": "Staff & Access",
  "/audit-log": "Audit Trail",
  "/settings": "Settings",
  "/settings/companies": "Companies & Locations",
  "/settings/branding": "White-label & Branding",
  "/settings/tax": "Tax Rates",
  "/settings/numbering": "Numbering",
};
